FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./app/main_api.py .

# Expose port
EXPOSE 8000

# Command to run the application at port 8000
CMD ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8000"]